### ISSUE TITLE
When can you release your source code? 

### ISSUE THREAD

**Issue by TimGor1997** [morbi25/rt3dcv-blog-article-spg#1]
@morbi25 Hello!
I wonder when can you release the code since I want to reproduce the experimental results and do some further research on SPG.

Looking forward for your reply. Thank you!

**Comment by morbi25** [comment]
Hi @TimGor1997,

sorry for the late response. As stated in the README.md file, this repository only contains a blog article that reviews the paper SPG: Unsupervised Domain Adaptation for 3D Object Detection via Semantic Point Generation. The blog article was created during a seminar at the Technical University of Munich. However, I am not the author of the original paper. 

As far as I know, the author's publications are listed [here](https://xharlie.github.io/publications/), but there is no repository that contains the code of SPG.
